name: General issue
description: Track work that is not a bug or feature request
title: "chore(scope): "
labels: ["triage"]
body:
  - type: textarea
    id: context
    attributes:
      label: Context
    validations:
      required: true
  - type: textarea
    id: outcome
    attributes:
      label: Desired outcome
